### PR TITLE
Perform no allocations

### PR DESCRIPTION
**Pull request by kriskowal**
Permit both compact and sparse arrays.

Return undefined value for undefined semantics.

Recommend major version due to backward incompatible treatment of arrays
and treatment of invalid input domain.

### CODE REVIEW

**Comment by Raynos** [comment]
This is much greatness.

lgtm. :+1:

**Comment by kriskowal** [comment]
In person, @raynos confides that the for(in) loop will deoptimize the function in V8. I’m pretty sure Object.keys is also deoptimized for the same reason, so swallowing the burden of running on the interpreter briefly in this function seems like a win. That being said, it would be good to A/B measure both approaches in the context of an optimizable function that calls into this to decide whether to do some work.

**Comment by gummesson** [comment]
Thanks for the pull request! 

I have another module that checks if an array is empty so I'm not sure if it makes sense to add that functionality to this one too. I could definitively drop the `typeOf` dependency though.

You could also use [is-empty](https://github.com/ianstormtaylor/is-empty), which doesn't have any external dependencies (although it works for more than just arrays and objects).

**Comment by brunoscopelliti** [comment]
hi @gummesson 
are you still considering this pull request?

would you at least fix the `! typeof` precedence bug at line 17? (`! typeof` is always `false`)

```
if (!obj || !typeof obj === 'object' || isArray(obj))
```

A good fix would be:

```
if (!obj || typeof obj != 'object' || isArray(obj))
```

This error is the cause for example of the following result:

```
isEmptyObject (function(){}); // true
```

that i don't think is the behaviour you want...

**Comment by gummesson** [comment]
Oops. I've fixed that nasty typo. Thanks for the heads up! :+1:

**Comment by kounelios13** [comment]
@kriskowal I believe that instead of returning undefined when the argument passed is not an object you should throw an error

**Comment by brunoscopelliti** [comment]
@kounelios13 You may want to check https://github.com/brunoscopelliti/is-object-really-empty. It does not throw, but always returns a boolean.

**Pull request closed without merging**
